name: Build and Release AARs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build AAR files
      run: ./gradlew assembleRelease

    - name: Upload AAR files
      uses: actions/upload-artifact@v2
      with:
        name: AAR-files
        path: |
          **/build/outputs/aar/*.aar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Ensure full history is fetched

    - name: Download AAR artifacts
      uses: actions/download-artifact@v2
      with:
        name: AAR-files
        path: .

    - name: Determine Tag Version
      id: get_version
      run: echo "::set-output name=version::v0.0.1"

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        release_name: Release ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh

    - name: Upload AAR to Release
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        for file in $(find . -name "*.aar"); do
          echo "Uploading $file..."
          gh release upload ${{ steps.get_version.outputs.version }} "$file" --clobber
        done
